name: create-organization-github-secrets-from-workflow
on:
  workflow_dispatch:
    inputs:
      organization:
        type: string
        default: 'devwithkrishna'
        description: 'The GitHub organization where the repository will be created.'
        required: true
      secret_value:
        type: string
        description: "Secret value to add"
        required: true
run-name: ${{ github.actor }} creating secrets in ${{ inputs.organization }}
jobs:
  create-organization-github-secrets-from-workflow:
  runs-on: ubuntu-latest
  steps:
  - name: git checkout
    uses: action/checkout@v4
  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: '3.11'
  - name: package installations
    run: |
      pip install pipenv
      pipenv install
  - name: get public key
    id: get-public-key
    env:
      GH_TOKEN: ${{ secrets.DEVWITHKRISHNA_PERSONAL_ACCESS_TOKEN }}
    run: |
      public_key=$(bash get_public_key.sh ${{inputs.organization}})
      echo "::set-output name=public_key::$public_key"
  - name: Encrypt secret
    id: encrypt-secret
    env:
      PUBLIC_KEY: ${{ steps.get-public-key.outputs.public_key }}
      SECRET_VALUE: ${{ inputs.secret_value }}
    run: |
      pipenv run python3 encrypt_secret.py
  - name: Completed
    run: |
      echo "program completed successfully"
