name: delete-organization-github-secrets-from-workflow
on:
  workflow_dispatch:
    inputs:
      organization:
        type: string
        default: 'devwithkrishna'
        description: 'The GitHub organization where the repository will be created.'
        required: true
      secret_name:
        type: string
        description: "Secret name to create/update on org level"
        required: true

run-name: ${{ github.actor }} deleting secret ${{ inputs.secret_name }} in ${{ inputs.organization }}
jobs:
  delete-organization-github-secrets-from-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: delete github org secret
        run: |
          bash delete_github_org_secret.sh ${{ inputs.organization }} ${{ inputs.secret_name}}
          echo "Secret deleted"
      - name: Completed
        run: |
          echo "program completed successfully"
