name: create-organization-github-secrets-from-workflow
on:
  workflow_dispatch:
  
run-name: using secrets in ${{ inputs.organization }}
jobs:
  create-organization-github-secrets-from-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: use secret
        env:
          TEST: ${{ secrets.TEST }}
        run: |
          echo "hello Everyone"
          echo $TEST >> cat.txt
      - name: text
        run: |
          ls -la
          cat cat.txt
      - name: Completed
        run: |
          echo "program completed successfully"
